# Generated by Django 4.1.7 on 2023-03-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='like'),
        ),
    ]
